### PR TITLE
adds distinct key batching

### PR DESCRIPTION
**Pull request by alexandrebodin**
Hi, References issue #34

This is a first attempt at making the necessary changes.

### CODE REVIEW

**Comment by alexandrebodin** [comment]
I should be using cacheKeyFn for distinct key checking I believe

**Comment by leebyron** [comment]
Thanks Alex for investigating this.

I'm a little worried about the overhead cost of doing this - wouldn't a simpler solution to be to not disable the request caching?

I'm trying to better understand the tradeoff so I can help evaluate this approach vs potential others.

**Comment by alexandrebodin** [comment]
I agree with you about the overhead.

Maybe we could make some cache clearing after a batch execution configuration ? adding some conf ?

**Comment by alexandrebodin** [comment]
Another idea.

What if we juste use the cache in the load function even if it is disabled and clear it after dispatch is disabled ? 
tYhat would yield the exact same result without overhead dont'you think ?

**Comment by leebyron** [comment]
Interesting. that would potentially be a breaking change, but so would the current implementation you have up here.

Consider the example:

```js
var a = myLoader.load("key");
var b = myLoader.load("key");
```

Should `a === b`? Clearly with caching on, the answer to that should be yes. But when caching is off, what should the answer be? Right now the answer is no, but perhaps it should be "it depends" - it depends on if batching is on. If batching is on, then should `a === b` only if these two load operations occur within the same batch? If the answer should be no then the current implementation is correct and it's up to the user to provide the right batching function that accepts non-deduped keys. If the answer should be yes, then we should do something like this and perhaps your suggestion of using a very short-lived cache is a cleaner implementation.

**Comment by leebyron** [comment]
I put up another possible approach to this at #46 - maybe useful to compare approaches

**Comment by alexandrebodin** [comment]
Hi,

I really like the approach at #46

Correct me if I'm wrong, but I would even argue that it would push for a more robust implementation of `batchLoadFn` on the developer side as It would prevent them from trying to modify data between each key load and / or add time sensitive data in their `batchLoadFn`.

I don't really see what would be a good use of having a non batch caching policy but, if we want to avoid a breaking change maybe  adding a config param such as `batchCaching` would do the trick. 
In `load` function, you would only cache if both are true  and clear after a `batch load` when caching is disabled.

**Pull request closed without merging**
